"""empty message

Revision ID: 93ebb2ae28f6
Revises: d0893edb3850
Create Date: 2018-10-10 19:20:28.394087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ebb2ae28f6'
down_revision = 'd0893edb3850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'registered_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'registered_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
